contract_wrappers.py: include all contracts. FIXME
FIXME because this isn't working entirely right.  Specifically, there
are quite a few linter errors:

- summary:
    - Spurious newline in generated return type for a method with multiple return values.
    - Missing definition for some tuples, one in `forwarder`, one in `dutch_auction`, and one in `coordinator`.
    - `forwarder`'s `marketBuyOrdersWithEth.call()` has weird return type `Union[[Tuple0xbb41e5b3, Tuple0xbb41e5b3], Union[HexBytes, bytes]]`
    - Overloaded method `safeTransferFrom()`, in both `erc721_token` and `dummy_erc721_token`, is resutling in two classes with the same name.
- from linter `black`:
    - summary:
        - both of the errors below seem to be a problem with an injected newline when generating a return value type for a method with multiple return values.
    - output:
        ```
        error: cannot format src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py: Cannot parse: 661:97:     def call(self, index_0: int, tx_params: Optional[TxParams] = None) -> [str, int, bytes, bool]
        error: cannot format src/zero_ex/contract_wrappers/order_validator/__init__.py: Cannot parse: 159:138:     def call(self, order: Tuple0x260219a2, taker_address: str, tx_params: Optional[TxParams] = None) -> [Tuple0xb1e4a1ae, Tuple0x8cfc0927]
        ```
- from linter `mypy`:
    - summary:
        - methods returning multiple values need to have return types like `List[typeA, typeB]`, not just `[typeA, typeB]`
        - missing definition for some tuples:
            - `Tuple0x260219a2` in `forwarder`
            - `Tuple0xbb41e5b3` in `dutch_auction`
            - `Tuple0x260219a2` in `coordinator`
        - `forwarder`'s `marketBuyOrdersWithEth.call()` has weird return type `Union[[Tuple0xbb41e5b3, Tuple0xbb41e5b3], Union[HexBytes, bytes]]`
        - erroneous redefinition of `SafeTransferFromMethod` (and attribute `safe_transfer_from`) in both `erc721_token` and `dummy_erc721_token`. looks like it's an overloaded method.
    - output:
        ```
        src/zero_ex/contract_wrappers/order_validator/__init__.py:175: error: Invalid type
        src/zero_ex/contract_wrappers/order_validator/__init__.py:243: error: Invalid type
        src/zero_ex/contract_wrappers/order_validator/__init__.py:311: error: Invalid type
        src/zero_ex/contract_wrappers/order_validator/__init__.py:511: error: Invalid type
        src/zero_ex/contract_wrappers/forwarder/__init__.py:83: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:86: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:152: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:155: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:160: error: Invalid type
        src/zero_ex/contract_wrappers/forwarder/__init__.py:214: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:217: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:409: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:411: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:469: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:471: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:476: error: Invalid type
        src/zero_ex/contract_wrappers/forwarder/__init__.py:528: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:530: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/erc721_token/__init__.py:557: error: Name 'SafeTransferFromMethod' already defined on line 274
        src/zero_ex/contract_wrappers/erc721_token/__init__.py:754: error: Name 'safe_transfer_from' already defined on line 750
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:127: error: Name 'Tuple0xbb41e5b3' is not defined
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:129: error: Name 'Tuple0xbb41e5b3' is not defined
        src/zero_ex/contract_wrappers/dummy_erc721_token/__init__.py:799: error: Name 'SafeTransferFromMethod' already defined on line 374
        src/zero_ex/contract_wrappers/dummy_erc721_token/__init__.py:1050: error: Name 'safe_transfer_from' already defined on line 1043
        src/zero_ex/contract_wrappers/coordinator/__init__.py:684: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:873: error: Invalid type
        ```
- from linter `pylint`:
    - summary:
        - parameters named `to` don't "conform to snake_case naming style"
        - undefinied tuple classes (repeat error from mypy)
        - Overloaded method `safeTransferFrom()`, on both `erc721_token` and `dummy_erc721_token`, generated as two same-named classes (repeat error from mypy)
    - output:
        ************* Module zero_ex.contract_wrappers.asset_proxy_owner
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:951:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:981:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:1008:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        ************* Module zero_ex.contract_wrappers.dutch_auction
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:127:10: E0602: Undefined variable 'Tuple0xbb41e5b3' (undefined-variable)
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:129:11: E0602: Undefined variable 'Tuple0xbb41e5b3' (undefined-variable)
        ************* Module zero_ex.contract_wrappers.coordinator
        src/zero_ex/contract_wrappers/coordinator/__init__.py:684:14: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        ************* Module zero_ex.contract_wrappers.dummy_erc721_token
        src/zero_ex/contract_wrappers/dummy_erc721_token/__init__.py:799:0: E0102: class already defined line 374 (function-redefined)
        ************* Module zero_ex.contract_wrappers.erc721_token
        src/zero_ex/contract_wrappers/erc721_token/__init__.py:557:0: E0102: class already defined line 274 (function-redefined)
        ************* Module zero_ex.contract_wrappers.i_asset_proxy
        src/zero_ex/contract_wrappers/i_asset_proxy/__init__.py:230:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/i_asset_proxy/__init__.py:259:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/i_asset_proxy/__init__.py:286:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        ************* Module zero_ex.contract_wrappers.forwarder
        src/zero_ex/contract_wrappers/forwarder/__init__.py:83:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:86:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:152:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:155:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:214:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:217:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:409:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:411:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:469:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:471:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:528:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:530:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)